version: '3.1'  # if no version is specified then v1 is assumed. Recommend v2 minimum

# docker run --name drupalec -p 8080:80 -d --network drupalnet drupal

# docker run -d --name pg-drupal --network drupalnet \
#     -e POSTGRES_DB=drupal \
#     -e POSTGRES_USER=user \
#     -e POSTGRES_PASSWORD=pass \
# postgres:11

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    # networks:
    #   - drupalnet
  drupal:
    image: drupal:latest
    ports:
      - 8080:80
    # networks:
    #   - drupalnet
    volumes:
      - "drupal-modules:/var/www/html/modules"
      - "drupal-profiles:/var/www/html/profiles"
      - "drupal-sites:/var/www/html/sites"
      - "drupal-themes:/var/www/html/themes"

# networks:
#   drupalnet:
#     driver: bridge

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: