version: "3.1" # if no version is specified then v1 is assumed. Recommend v2 minimum

services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    networks:
      - drupalnet
    volumes:
      - "drupal-data:/var/lib/postgresql/data"
  drupal:
    build: .
    image: custom-drupal
    ports:
      - 8080:80
    networks:
      - drupalnet
    volumes:
      - "drupal-modules:/var/www/html/modules"
      - "drupal-profiles:/var/www/html/profiles"
      - "drupal-sites:/var/www/html/sites"
      - "drupal-themes:/var/www/html/themes"

networks:
  drupalnet:
    driver: bridge

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
